spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=postgres
spring.datasource.password=Ekta123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.port=8080

jwt.secret=jwt.secret=8Fh3Kp9Lm2Qx7Vt5Nc1Rw6Zy4Aa9Bs0Cd5Ef7Gh8Ij0Kl2Mn
jwt.expiration=86400000